In [2]:
import pandas as pd
pd.read_csv(r"C:\Users\Dell\Downloads\AmazonFoodReviews.csv")

C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
...        ...         ...             ...                              ...   
568449  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter   
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer   
568451  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"   
568452  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"   
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17   

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                          1                       1      5  1303862400   
1                          0                       0      1  1346976000   
2                          1                       1      4  1219017600   
3                          3                       3      2  1307923200   
4                          0                       0      5  1350777600   
...                      ...                     ...    ...         ...   
568449                     0                       0      5  1299628800   
568450                     0                       0      2  1331251200   
568451                     2                       2      5  1329782400   
568452                     1                       1      5  1331596800   
568453                     0                       0      5  1338422400   

                                   Summary  \
0                    Good Quality Dog Food   
1                        Not as Advertised   
2                    "Delight" says it all   
3                           Cough Medicine   
4                              Great taffy   
...                                    ...   
568449                 Will not do without   
568450                        disappointed   
568451            Perfect for our maltipoo   
568452  Favorite Training and reward treat   
568453                         Great Honey   

                                                     Text  
0       I have bought several of the Vitality canned d...  
1       Product arrived labeled as Jumbo Salted Peanut...  
2       This is a confection that has been around a fe...  
3       If you are looking for the secret ingredient i...  
4       Great taffy at a great price.  There was a wid...  
...                                                   ...  
568449  Great for sesame chicken..this is a good if no...  
568450  I'm disappointed with the flavor. The chocolat...  
568451  These stars are small, so you can give 10-15 o...  
568452  These are the BEST treats for training and rew...  
568453  I am very satisfied ,product is as advertised,...  

[568454 rows x 10 columns]

In [3]:
df  = pd.read_csv(r"C:\Users\Dell\Downloads\AmazonFoodReviews.csv")

In [4]:
df = df.drop(['Id','ProductId','UserId','ProfileName','HelpfulnessNumerator','HelpfulnessDenominator'],axis=1)

In [5]:
df = df.drop(['Time','Text'],axis=1)

In [6]:
df.head()

Score                Summary
0      5  Good Quality Dog Food
1      1      Not as Advertised
2      4  "Delight" says it all
3      2         Cough Medicine
4      5            Great taffy

In [7]:
df = df.rename(columns={'Score':'Y','Summary':'X'})

In [8]:
df.Y.value_counts()

Y
5    363122
4     80655
1     52268
3     42640
2     29769
Name: count, dtype: int64

In [9]:
df.Y.replace({1:0,2:0,3:1,4:2,5:2},inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_18468\2128778323.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Y.replace({1:0,2:0,3:1,4:2,5:2},inplace=True)


In [10]:
df.Y.value_counts()

Y
2    443777
0     82037
1     42640
Name: count, dtype: int64

In [11]:
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')
from keras.layers import Dense, SimpleRNN, Embedding
from keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer # assign uoique number(id) to each unique word
from keras.preprocessing.sequence import pad_sequences

In [12]:
df.head(
)

Y                      X
0  2  Good Quality Dog Food
1  0      Not as Advertised
2  2  "Delight" says it all
3  0         Cough Medicine
4  2            Great taffy

In [13]:
df.X = df.X.str.lower()

In [14]:
df_X = df.iloc[:,1]
df_Y = df.iloc[:,0]
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(df.X,df.Y, test_size=0.2)

In [26]:
df.X

0                      good quality dog food
1                          not as advertised
2                      "delight" says it all
3                             cough medicine
4                                great taffy
                         ...                
568449                   will not do without
568450                          disappointed
568451              perfect for our maltipoo
568452    favorite training and reward treat
568453                           great honey
Name: X, Length: 568454, dtype: object

In [15]:

train_y=to_categorical(train_y)

In [16]:
df.X = df.X.astype(str)

In [17]:
df.X

0                      good quality dog food
1                          not as advertised
2                      "delight" says it all
3                             cough medicine
4                                great taffy
                         ...                
568449                   will not do without
568450                          disappointed
568451              perfect for our maltipoo
568452    favorite training and reward treat
568453                           great honey
Name: X, Length: 568454, dtype: object

In [18]:
max_num_words = 10000 # hyperparameter, select 10000 unique word from entire corpus
seq_len = 50          # hyperparameter, from each record select 50 words out of above 10000 
embedding_size = 100  # hyperparameter, vector length of each word
tokenizer = Tokenizer (num_words = max_num_words)
tokenizer.fit_on_texts(df.X) # on full data

In [19]:
df.X = df.X.astype(str)
train_x = train_x.astype(str)
test_x = test_x.astype(str)
import numpy as np

In [20]:
# Ensure train_x and test_x are lists of strings
if isinstance(train_x, np.ndarray):
    train_x = train_x.tolist()

if isinstance(test_x, np.ndarray):
    test_x = test_x.tolist()

# Convert texts to sequences
train_x = tokenizer.texts_to_sequences(train_x)
train_x = pad_sequences(train_x, maxlen=seq_len)

test_x = tokenizer.texts_to_sequences(test_x)
test_x = pad_sequences(test_x, maxlen=seq_len)


In [21]:
model = Sequential()
model.add(Embedding(input_dim = max_num_words,
                   input_length = seq_len,
                   output_dim = embedding_size))

In [22]:
model.add(SimpleRNN(64))
model.add(Dense(3, activation='softmax'))
adam = tf.keras.optimizers.Adam(learning_rate=0.001) 
model.compile(optimizer = adam, loss = 'categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.fit(train_x, train_y, epochs = 5, batch_size = 128, validation_split = .2)

Epoch 1/5
2843/2843 ━━━━━━━━━━━━━━━━━━━━ 70s 24ms/step - accuracy: 0.8413 - loss: 0.4353 - val_accuracy: 0.8789 - val_loss: 0.3387
Epoch 2/5
2843/2843 ━━━━━━━━━━━━━━━━━━━━ 74s 26ms/step - accuracy: 0.8912 - loss: 0.2987 - val_accuracy: 0.8867 - val_loss: 0.3217
Epoch 3/5
2843/2843 ━━━━━━━━━━━━━━━━━━━━ 66s 23ms/step - accuracy: 0.9069 - loss: 0.2589 - val_accuracy: 0.8885 - val_loss: 0.3216
Epoch 4/5
2843/2843 ━━━━━━━━━━━━━━━━━━━━ 68s 24ms/step - accuracy: 0.9170 - loss: 0.2322 - val_accuracy: 0.8916 - val_loss: 0.3229
Epoch 5/5
2843/2843 ━━━━━━━━━━━━━━━━━━━━ 69s 24ms/step - accuracy: 0.9236 - loss: 0.2148 - val_accuracy: 0.8904 - val_loss: 0.3313


In [24]:
pred = model.predict(test_x)
pred_classes = pred.argmax(axis=1)
from sklearn.metrics import confusion_matrix, classification_report
tab = confusion_matrix(test_y, pred_classes)
print('confusion_matrix:')
print(tab)
print('------------------------------------------------------')
print('classification_report:')
print(classification_report(test_y, pred_classes))

3553/3553 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step
confusion_matrix:
[[11902  1348  3135]
 [ 1632  3434  3388]
 [ 1623  1241 85988]]
------------------------------------------------------
classification_report:
              precision    recall  f1-score   support

           0       0.79      0.73      0.75     16385
           1       0.57      0.41      0.47      8454
           2       0.93      0.97      0.95     88852

    accuracy                           0.89    113691
   macro avg       0.76      0.70      0.73    113691
weighted avg       0.88      0.89      0.89    113691



In [35]:
print(type(train_x))
print(type(test_x))


<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
import tensorflow as tf
from keras.layers import Dense, LSTM, Embedding
from keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')


df = pd.read_csv(r"C:\Users\Dell\Downloads\AmazonFoodReviews.csv")
df = df.drop(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator'], axis=1)
df = df.drop(['Time', 'Text'], axis=1)
df = df.rename(columns={'Score': 'Y', 'Summary': 'X'})


df.Y.replace({1: 0, 2: 0, 3: 1, 4: 2, 5: 2}, inplace=True)

# Preprocess text data
df.X = df.X.str.lower()
df.X = df.X.astype(str)

# Split data into train and test sets
train_x, test_x, train_y, test_y = train_test_split(df.X, df.Y, test_size=0.2)

# Convert target labels to categorical
train_y = to_categorical(train_y)

# Tokenization and padding
max_num_words = 10000
seq_len = 50
embedding_size = 100
tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(df.X)

train_x = tokenizer.texts_to_sequences(train_x)
train_x = pad_sequences(train_x, maxlen=seq_len)

test_x = tokenizer.texts_to_sequences(test_x)
test_x = pad_sequences(test_x, maxlen=seq_len)

# Build the model with LSTM
model = Sequential()
model.add(Embedding(input_dim=max_num_words, input_length=seq_len, output_dim=embedding_size))
model.add(LSTM(64))
model.add(Dense(3, activation='softmax'))

# Compile the model
adam = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_x, train_y, epochs=5, batch_size=128, validation_split=0.2)

# Evaluate the model
pred = model.predict(test_x)
pred_classes = pred.argmax(axis=1)

tab = confusion_matrix(test_y, pred_classes)
print('Confusion Matrix:')
print(tab)
print('------------------------------------------------------')
print('Classification Report:')
print(classification_report(test_y, pred_classes))


print(type(train_x))
print(type(test_x))
